### ISSUE TITLE
need subdomains

### ISSUE THREAD

**Issue by jcomeauictx** [jcomeauictx/myturnb#14]
@DavidStodolsky, I need 3 subdomains added to the myturn.mobi zone:

`alpha`, for testing the latest modifications to the code.
`beta`, for the code passing `alpha` test but still not robust enough for use
`baseline`, for the code as I inherited it, with just those modifications that reenabled the report page.

I will use the base domain `myturn.mobi` for the code that passes beta testing.

you could make it easier just by adding a wildcard `*` entry in the zonefile pointing to myturn.mobi's IP address (an `A` record). then I can make new subdomains just by adding virtual hosts to nginx.

**Comment by DavidStodolsky** [comment]
Did it
