### ISSUE TITLE
New Group name does not appear

### ISSUE THREAD

**Issue by DavidStodolsky** [jcomeauictx/myturnb#30]
After entering a new Group name on one phone and having it appear in the Group field,
the name fails to appear on another phone. The Group field remains empty.
Android phones in this test.
This occurred immediately after a successful one minute demonstration of Myturn on these phones.

Problem persists after reload of the Myturn page or restart of the phone.

This is a high priority issue, since it prevents starting of the app.

**Comment by jcomeauictx** [comment]
I understand it's high priority but it's intermittent. so I was hoping to be able to fix it with a total rewrite, which I've been working on at https://github.com/jcomeauictx/myturn/tree/alpha

the current code is too convoluted for me to figure it out. but if it's a show-stopper, I guess I'll have to drop the rewrite for now and focus on it.

**Comment by jcomeauictx** [comment]
@DavidStodolsky did you use the same group name on the 2nd test as on the first?

**Comment by jcomeauictx** [comment]
never mind, it doesn't seem to matter. this is probably a new bug, caused by some recent modification. should I revert to an older version on myturn.mobi?

**Comment by DavidStodolsky** [comment]
It is high priority, but time is not short.
Anyway, most of the time things work.
I would just continue with the rewrite.

The start up has always been troublesome.
I don't recall, if this particular bug appeared before.
So, it isn't clear that it is caused by a recent modification.
The rewrite minimizes work in the long run, so that is probably the best option.

**Comment by jcomeauictx** [comment]
@DavidStodolsky I can only duplicate the problem on myturn.mobi. http://beta.myturn.mobi does not exhibit this behavior, even though it's running the same code. I don't know why this is, but for now just use beta until I figure it out.

**Comment by jcomeauictx** [comment]
I restarted all 3 services: `systemctl restart myturn@alpha`,  `beta` and `release`. they are all working now. at first I tried copying the node_modules from alpha to beta, but that broke beta for a few minutes until I restarted. `release` still has different versions of some modules, but I guess it isn't what caused the problem since it's working now.

I'm convinced that nodejs is not the best technology for a stable application, at least not combined with `npm` as installer; there is no way to guarantee that the underlying modules won't be changed to broken ones on any given installation. I'm going to switch the backend to Python for my rewrite.

**Comment by jcomeauictx** [comment]
perhaps the application should be restarted regularly, there might be a memory leak or other programming issue causing the app to randomly fail. daily or weekly? is there an ideal time?

**Comment by DavidStodolsky** [comment]
Let's try a weekly restart. This can be switched to daily as a diagnostic, if we encounter problems.
Sunday morning at 1:00 hours should avoid disrupting business users.

**Comment by jcomeauictx** [comment]
is that 01:00 Copenhagen time?

**Comment by DavidStodolsky** [comment]
yes

**Comment by jcomeauictx** [comment]
because JavaScript has such crappy handling of timezones, I'm going to use midnight UTC, which will be 1:00 in Copenhagen during the winter and 2:00 in the summer. it will also be Saturday afternoon in the US, another highly unlikely time for a business meeting.

**Comment by jcomeauictx** [comment]
code added, tested locally, and is now running on alpha.myturn.mobi.

> jcomeau@old.myturn:~$ sudo grep restart /var/log/syslog
> Jul  8 04:29:22 myturn4b-1488012845910-512mb-ams3-01 myturn-alpha[26177]: restarting in 588637144 milliseconds
