### ISSUE TITLE
Synchrony between devices with and without vibration?

### ISSUE THREAD

**Issue by DavidStodolsky** [jcomeauictx/myturnb#35]
A the moment, users of phones and of laptops get a different experience. A first improvement would make them more similar in behavior. The vibrations appearing on the phones could be accompanied by screen flashes, so users of laptops and tablets would also be getting feedback. The current beep sound could be rendered as flashes. The current clicks every second would be eliminated. 

In less brightly lit locations, these flashes could be used to identify the current speaker in a large group. However, the flashes every couple of seconds should be retained when the button is pressed, perhaps with a less obvious differentiation. The objective is to provide the user with feedback on button press, but avoid making it public.

**Comment by jcomeauictx** [comment]
screen flashes instead of vibration was implemented in pyturn. will not be duplicated in myturnb.
